packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^5.2.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@d-fischer/typed-event-emitter': ^3.3.3
  '@iconify-json/circle-flags': ^1.2.8
  '@iconify-json/fluent': ^1.2.29
  '@iconify-json/fluent-emoji-flat': ^1.2.5
  '@iconify-json/lucide': ^1.2.63
  '@iconify-json/simple-icons': ^1.2.48
  '@internationalized/date': ^3.8.2
  '@neoconfetti/vue': ^2.2.1
  '@number-flow/vue': ^0.4.8
  '@nuxt/devtools': ^2.6.3
  '@nuxt/ui': ^3.3.2
  '@nuxtjs/i18n': ^10.0.6
  '@paralleldrive/cuid2': ^2.2.2
  '@pinia/nuxt': ^0.11.2
  '@tailwindcss/vite': ^4.1.12
  '@telegram-apps/init-data-node': ^2.0.10
  '@telegram-apps/sdk-vue': ^2.0.30
  '@tsparticles/engine': ^3.9.1
  '@tsparticles/slim': ^3.9.1
  '@tsparticles/vue3': ^3.0.1
  '@types/howler': ^2.2.12
  '@types/node': ^24.3.0
  '@types/pg': ^8.15.5
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vue/tsconfig': ^0.8.1
  '@vueuse/components': ^13.7.0
  '@vueuse/core': ^13.7.0
  '@vueuse/nuxt': ^13.7.0
  changelogen-monorepo: ^0.5.0
  date-fns: ^4.1.0
  dotenv: ^17.2.1
  drizzle-cuid2: ^2.1.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  eruda: ^3.4.3
  eslint: ^9.34.0
  grammy: ^1.38.1
  howler: ^2.2.4
  husky: ^9.1.7
  lint-staged: ^16.1.5
  nuxt: ^4.0.3
  nuxt-auth-utils: ^0.5.23
  pg: ^8.16.3
  pinia: ^3.0.3
  pixi.js: ^8.12.0
  playwright: ^1.55.0
  tailwindcss: ^4.1.12
  tailwindcss-motion: ^1.1.1
  typescript: ^5.9.2
  unplugin-auto-import: ^20.0.0
  unplugin-icons: ^22.2.0
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.3
  vite-plugin-terminal: ^1.3.0
  vite-plugin-vue-devtools: ^8.0.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vitest-browser-vue: ^1.1.0
  vue: ^3.5.19
  vue-i18n: ^11.1.11
  vue-router: ^4.5.1
  vue-tsc: ^3.0.6
  zod: ^4.1.0
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
onlyBuiltDependencies:
  - protobufjs
supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]
